---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v0/auth":
    post:
      summary: Creates a user
      tags:
      - Auth
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            password:
              type: string
          required:
          - name
          - email
          - password
      responses:
        '200':
          description: user created
        '422':
          description: error creating user
  "/api/v0/users":
    get:
      summary: get all users
      tags:
      - Users
      consumes:
      - application/json
      - application/xml
      responses:
        '200':
          description: list of users
